import { Navbar } from '@/components'
import '../css/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dz startup explorer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
